package ch.zhaw.moba1.guesswho

val originalCharacters = arrayOf(
    Character(
        img = R.drawable.rubert,
        name = "Rubert",
        hairColor = "red",
        hasBlueEyes = true,
        hasFacialHair = true,
        hasLightSkin = true,
        isBald = true,
        isMale = true,
        wearsGlasses = false,
        wearsHat = false,
        isFaceDown = false
    ),
    Character(
        img = R.drawable.benjamin,
        name = "Benjamin",
        hairColor = "red",
        hasBlueEyes = true,
        hasFacialHair = false,
        hasLightSkin = true,
        isBald = false,
        isMale = true,
        wearsGlasses = true,
        wearsHat = true,
        isFaceDown = false
    ),
    Character(
        img = R.drawable.chris,
        name = "Chris",
        hairColor = "blond",
        hasBlueEyes = false,
        hasFacialHair = false,
        hasLightSkin = false,
        isBald = false,
        isMale = true,
        wearsGlasses = true,
        wearsHat = false,
        isFaceDown = false
    ),
    Character(
        img = R.drawable.ron,
        name = "Ron",
        hairColor = "black",
        hasBlueEyes = true,
        hasFacialHair = true,
        hasLightSkin = true,
        isBald = false,
        isMale = true,
        wearsGlasses = false,
        wearsHat = false,
        isFaceDown = false
    ),
    Character(
        img = R.drawable.tyron,
        name = "Tyron",
        hairColor = "blond",
        hasBlueEyes = false,
        hasFacialHair = true,
        hasLightSkin = true,
        isBald = true,
        isMale = true,
        wearsGlasses = true,
        wearsHat = false,
        isFaceDown = false
    ),
    Character(
        img = R.drawable.dembe,
        name = "Dembe",
        hairColor = "gray",
        hasBlueEyes = false,
        hasFacialHair = true,
        hasLightSkin = false,
        isBald = true,
        isMale = true,
        wearsGlasses = false,
        wearsHat = false,
        isFaceDown = false
    ),
    Character(
        img = R.drawable.zane,
        name = "Zane",
        hairColor = "black",
        hasBlueEyes = false,
        hasFacialHair = false,
        hasLightSkin = false,
        isBald = false,
        isMale = true,
        wearsGlasses = false,
        wearsHat = true,
        isFaceDown = false
    ),
    Character(
        img = R.drawable.nicholas,
        name = "Nicholas",
        hairColor = "gray",
        hasBlueEyes = true,
        hasFacialHair = true,
        hasLightSkin = true,
        isBald = true,
        isMale = true,
        wearsGlasses = true,
        wearsHat = false,
        isFaceDown = false
    ),
    Character(
        img = R.drawable.emily,
        name = "Emily",
        hairColor = "red",
        hasBlueEyes = false,
        hasFacialHair = false,
        hasLightSkin = true,
        isBald = false,
        isMale = false,
        wearsGlasses = true,
        wearsHat = true,
        isFaceDown = false
    ),
    Character(
        img = R.drawable.kristina,
        name = "Kristina",
        hairColor = "blond",
        hasBlueEyes = false,
        hasFacialHair = false,
        hasLightSkin = true,
        isBald = false,
        isMale = false,
        wearsGlasses = false,
        wearsHat = true,
        isFaceDown = false
    ),
    Character(
        img = R.drawable.olivia,
        name = "Olivia",
        hairColor = "blond",
        hasBlueEyes = true,
        hasFacialHair = false,
        hasLightSkin = false,
        isBald = false,
        isMale = false,
        wearsGlasses = true,
        wearsHat = false,
        isFaceDown = false
    ),
    Character(
        img = R.drawable.dolores,
        name = "Dolores",
        hairColor = "gray",
        hasBlueEyes = true,
        hasFacialHair = false,
        hasLightSkin = true,
        isBald = false,
        isMale = false,
        wearsGlasses = true,
        wearsHat = false,
        isFaceDown = false
    ),
    Character(
        img = R.drawable.monica,
        name = "Monica",
        hairColor = "black",
        hasBlueEyes = false,
        hasFacialHair = false,
        hasLightSkin = false,
        isBald = false,
        isMale = false,
        wearsGlasses = false,
        wearsHat = false,
        isFaceDown = false
    ),
    Character(
        img = R.drawable.viktoria,
        name = "Viktoria",
        hairColor = "black",
        hasBlueEyes = true,
        hasFacialHair = false,
        hasLightSkin = true,
        isBald = false,
        isMale = false,
        wearsGlasses = false,
        wearsHat = false,
        isFaceDown = false
    ),
    Character(
        img = R.drawable.dorothy,
        name = "Dorothy",
        hairColor = "gray",
        hasBlueEyes = false,
        hasFacialHair = false,
        hasLightSkin = false,
        isBald = false,
        isMale = false,
        wearsGlasses = false,
        wearsHat = true,
        isFaceDown = false
    ),
    Character(
        img = R.drawable.carmen,
        name = "Carmen",
        hairColor = "red",
        hasBlueEyes = true,
        hasFacialHair = false,
        hasLightSkin = true,
        isBald = false,
        isMale = false,
        wearsGlasses = false,
        wearsHat = true,
        isFaceDown = false
    )
)
